---
- name: Create EC2 Instances for JBoss Demo
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  roles:
    - ec2_common

- name: Install JBoss and Deploy Apps
  hosts: new_host

  roles:
    - jboss-standalone
    - java-app
