---
- name: Create EC2 Instances for JBoss Demo
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  roles:
    - ec2_common

- name: pause this playbook to allow Tower's inventory to refresh
  pause:
    minutes: 2

- name: Install JBoss and Deploy Apps
  hosts: all

  roles:
    - jboss-standalone
    - java-app
